services:
  app:
    image: laravel-slim-app:latest # Nama image yang Akang build
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      # 1. Mount source code ke direktori aplikasi
      - ./:/var/www/html
      
      # 2. Hapus default.conf (dengan cara me-mount file kosong atau config baru)
      # Kita langsung timpa file default.conf di dalam container dengan laravel.conf lokal
      - ./laravel.conf:/etc/nginx/conf.d/default.conf
      
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
